### ISSUE TITLE
Compatibilité S3 des pipelines

### ISSUE THREAD

**Issue by JoMessina** [php-etl/csv-plugin#17]
Réaliser l'écriture et la lecture d'un fichier sur un système amazon cloud S3, voici la démarche suivi :

- Créer un nouveau projet

- Lancer un conteneur docker avec minio avec la configuration suivante 
  ```
  s3:
    image: quay.io/minio/minio
    ports: 
      - ${MINIO_PORT_0:-9000}:9000
      - ${MINIO_PORT_1:-9001}:9001
    command: [ 'server', '/data', '--console-address', ':9001' ]
    volumes:
      - 'minio_data:/data'
  volumes:
  minio_data:
  ```

- Accéder à l'interface Minio et aller dans l'onglet bucket pour créer un nouveau bucket
![image](https://user-images.githubusercontent.com/99172532/231454339-c386881e-32bd-4bab-8f05-280e81a870f5.png)

- Créer des clés d'accès pour minio, ces informations servirons pour la configuration du client S3 (key et secret).
![image](https://user-images.githubusercontent.com/99172532/231454571-a29dddf8-ddb9-447c-879b-d6c91b5695cd.png)

- composer require php-etl/satellite

- composer require php-etl/csv-plugin

- Configuration satellite.yaml : 
  ```
  satellites:
      csv_to_csv:
          label: 'CSV to CSV'
          filesystem:
              path: build
          pipeline:
              steps:
                  - csv:
                        extractor:
                            file_path: '../data/input/test.csv'
                  - csv:
                        loader:
                            file_path: 's3://s3filesystemtest/output/test.csv'
  ```

- php bin/satellite build src/satellite.yaml

- Ajouter le code suivant dans le fichier pipeline.php généré par le build 
  ```
  $client = new S3Client([
        'version'     => 'latest',
        'region'      => 'us-west-2',
        'endpoint' => 'http://127.0.0.1:19000',
        'credentials' => [
            'key'    => 'ZDJ2tvFLyUIPX61P',
            'secret' => 'sub9RRBtSZH3yImPckBKqCUmSbdyuwua',
        ],
    ]);
  $client->registerStreamWrapper();
  ```

- php bin/satellite run:pipeline build/
    
Résultat :
![image](https://user-images.githubusercontent.com/99172532/231455101-9aa1cbc9-0257-4394-9561-4a260e5e1672.png)
![image](https://user-images.githubusercontent.com/99172532/231455146-03f68303-c5c6-4924-8635-f6070bf40404.png)
![image](https://user-images.githubusercontent.com/99172532/231455173-52132c7d-5640-4593-8fd7-6a0c58a31fe5.png)
